FROM  python:3.9.16-slim-bullseye
WORKDIR /backend

ENV PYTHONDONTWRITTENBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY . .
RUN pip install -r requirments.txt

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
